### ISSUE TITLE
Update to latest ent version

### ISSUE THREAD

**Issue by hagiali** [Grief-Code/GriefNetwork-Bot#2]
Default ENT repository is LUNA branch and you used, but the patched and with more fixes/features is the branch ENT https://github.com/uakfdotb/ent-ghost/tree/ent
Please study, this will not take too much to update.

**Comment by Grief-Code** [comment]
The majority of this patches where more implementation of stats commands.
I may will switch in the future to the branch.

**Comment by hagiali** [comment]
i'll make a repo with latest ENT branch with ur all changes.

**Comment by hagiali** [comment]
Finaly done 👍 https://github.com/hagiali/GamersHost-Bot
i test and its work. Is a good ideea to make a branch for me and to do a pull request?

**Comment by Grief-Code** [comment]
I will look into it this weekend and merge it over. You won't need to do a pull request.

**Comment by hagiali** [comment]
you just added new commits. Why you don't start a test bot with last merged and last version ?

**Comment by Grief-Code** [comment]
Because i hadn't yet time looking deeper into this and my partner requested this feature. I will merge with the ent source the upcoming weekend.

**Comment by hagiali** [comment]
Updated again,

**Comment by Grief-Code** [comment]
I've created a pull request:
https://github.com/Grief-Code/GriefNetwork-Bot/pull/7
Everything furhere will be handled trhough the pull request.
Thanks for your help.
