### ISSUE TITLE
Missing table

### ISSUE THREAD

**Issue by hagiali** [Grief-Code/GriefNetwork-Bot#4]
In this line, 'GamePlayerSummaryCheck':
https://github.com/gamershost/GamersHost-Bot/blob/master/ghostdbmysql.cpp#L1159
is involved 'gametrack' table, but is missing from main DB

**Comment by Grief-Code** [comment]
I do not have it eithere on my database as it is not mandatory, however, I will include it.

**Comment by hagiali** [comment]
this file update the 'gametrack' table https://github.com/gamershost/GamersHost-Bot/blob/master/cron_functions.php
