### ISSUE TITLE
?

### ISSUE THREAD

**Issue by TemKaSD** [Grief-Code/GriefNetwork-Bot#6]
![2017-02-26_040201](https://cloud.githubusercontent.com/assets/6318282/23333549/f43d4c92-fbd8-11e6-82b6-0c90f5f8481f.png)

**Comment by Grief-Code** [comment]
?

**Comment by TemKaSD** [comment]
@Grief-Code no connection yes

**Comment by Grief-Code** [comment]
This is debug message for mysql, you can ignore it.

**Comment by TemKaSD** [comment]
@Grief-Code Why not create the game?
